1. Importing Libraries

In [24]:
import numpy as np
import pandas as pd

In [25]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 70D6-B03A

 Directory of C:\Users\MWAMBA\Clustering_HO

12/13/2022  12:29 PM    <DIR>          .
12/13/2022  12:29 PM    <DIR>          ..
12/13/2022  12:21 PM    <DIR>          .ipynb_checkpoints
12/13/2022  12:29 PM            12,868 Clustering.ipynb
12/13/2022  12:12 PM            23,701 LEO1_LLA_Position.csv
12/13/2022  12:12 PM        11,102,849 NTN.csv
               3 File(s)     11,139,418 bytes
               3 Dir(s)  55,426,060,288 bytes free

In [26]:
# Loading UE Data
UE_data = pd.read_csv('NTN.csv')

In [31]:
UE_data

,Index,Latitude,Longitude,Time,Azimuth,Elevation,Range,Free Space Loss,Prop Loss,Rcvd. Iso. Power,Carrier Power at Rcvr Input,Flux Density,g/T,C/No,C/N,Eb/No,Propagation Delay,Propagation Distance,Spectral Flux Density
0,0,-1.4504,-117.3632,0.000000,143.359147,-57.604110,358.769054,166.771443,166.771443,-136.771443,-136.771443,-92.088398,20,51.827696,36.776196,39.786496,0.001197,358.769054,-167.139898
1,0,-1.4504,-117.3632,18.568969,157.262179,-45.000008,434.799789,168.440933,168.440933,-138.440933,-138.440933,-93.757888,20,50.158206,35.106706,38.117006,0.001450,434.799938,-168.809388
2,1,2.3699,-117.8514,0.000000,269.924452,-47.333303,416.580662,168.069125,168.069125,-138.069125,-138.069125,-93.386081,20,50.530013,35.478514,38.488814,0.001390,416.580662,-168.437581
3,1,2.3699,-117.8514,18.758000,244.785905,-45.001232,434.831293,168.441559,168.441559,-138.441559,-138.441559,-93.758514,20,50.157580,35.106080,38.116380,0.001450,434.831293,-168.810014
4,2,1.8450,-117.6596,0.000000,267.581620,-53.925974,375.984337,167.178538,167.178538,-137.178538,-137.178538,-92.495494,20,51.420601,36.369101,39.379401,0.001254,375.984337,-167.546993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,19997,1.2025,-118.3447,18.758000,218.413405,-45.002412,434.778722,168.440509,168.440509,-138.440509,-138.440509,-93.757464,20,50.158630,35.107130,38.117430,0.001450,434.778722,-168.808964
39996,19998,1.0002,-118.0486,0.000000,240.075273,-58.653151,354.432567,166.665816,166.665816,-136.665816,-136.665816,-91.982771,20,51.933323,36.881823,39.892123,0.001182,354.432567,-167.034271
39997,19998,1.0002,-118.0486,24.977000,210.115505,-45.000073,434.793659,168.440807,168.440807,-138.440807,-138.440807,-93.757763,20,50.158332,35.106832,38.117132,0.001450,434.793659,-168.809262
39998,19999,0.9811,-114.7689,0.000000,4.072684,-53.099800,380.300263,167.277676,167.277676,-137.277676,-137.277676,-92.594631,20,51.321463,36.269963,39.280263,0.001269,380.300263,-167.646131
39999,19999,0.9811,-114.7689,76.550801,173.801747,-45.002815,434.769376,168.440343,168.440343,-138.440343,-138.440343,-93.757298,20,50.158796,35.107296,38.117596,0.001450,434.770400,-168.808798

In [28]:
LEO_data = pd.read_csv('LEO1_LLA_Position.csv')

In [30]:
LEO_data

     Time (UTCG)  Lat (deg)  Lon (deg)    Alt (km)  speed (km/sec)
0              0      0.127   -116.637  300.000104        7.301502
1              1      0.159   -116.583  300.000163        7.301502
2              2      0.191   -116.529  300.000235        7.301502
3              3      0.223   -116.475  300.000320        7.301502
4              4      0.254   -116.421  300.000418        7.301502
..           ...        ...        ...         ...             ...
596          596     17.881    -83.178  302.001249        7.299989
597          597     17.906    -83.118  302.006811        7.299984
598          598     17.932    -83.058  302.012376        7.299980
599          599     17.958    -82.997  302.017943        7.299976
600          600     17.983    -82.937  302.023512        7.299972

[601 rows x 5 columns]

In [33]:
UE_data.shape

(40000, 19)

In [34]:
UE_data.head(2)

,Index,Latitude,Longitude,Time,Azimuth,Elevation,Range,Free Space Loss,Prop Loss,Rcvd. Iso. Power,Carrier Power at Rcvr Input,Flux Density,g/T,C/No,C/N,Eb/No,Propagation Delay,Propagation Distance,Spectral Flux Density
0,0,-1.4504,-117.3632,0.000000,143.359147,-57.604110,358.769054,166.771443,166.771443,-136.771443,-136.771443,-92.088398,20,51.827696,36.776196,39.786496,0.001197,358.769054,-167.139898
1,0,-1.4504,-117.3632,18.568969,157.262179,-45.000008,434.799789,168.440933,168.440933,-138.440933,-138.440933,-93.757888,20,50.158206,35.106706,38.117006,0.001450,434.799938,-168.809388

In [38]:
UE_data['Index'].unique()

array([    0,     1,     2, ..., 19997, 19998, 19999], dtype=int64)

In [37]:
UE_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Index                        40000 non-null  int64
 1   Latitude                     40000 non-null  float64
 2   Longitude                    40000 non-null  float64
 3   Time                         40000 non-null  float64
 4   Azimuth                      40000 non-null  float64
 5   Elevation                    40000 non-null  float64
 6   Range                        40000 non-null  float64
 7   Free Space Loss              40000 non-null  float64
 8   Prop Loss                    40000 non-null  float64
 9   Rcvd. Iso. Power             40000 non-null  float64
 10  Carrier Power at Rcvr Input  40000 non-null  float64
 11  Flux Density                 40000 non-null  float64
 12  g/T                          40000 non-null  int64
 13  C/No                         40000 non-null  float64
 14  C/N                          40000 non-null  float64
 15  Eb/No                        40000 non-null  float64
 16  Propagation Delay            40000 non-null  float64
 17  Propagation Distance         40000 non-null  float64
 18  Spectral Flux Density        40000 non-null  float64
dtypes: float64(17), int64(2)
memory usage: 5.8 MB

In [40]:
# Max Latitude
UE_data['Latitude'].max()

3.0498

In [42]:
# Max Longitude
UE_data['Longitude'].max()

-113.502